package com.zaycodes;
import java.util.*;
public class Game {

    public int startGame(){
        Scanner input = new Scanner(System.in);

        //start game
        System.out.println("Welcome to Rochambeau by Isiah Daniels! Enter 1, 2 or 3 for rock, paper and scissors, respectively.");

        //create a variable to hold the user response using the Scanner object. The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)

        int playerPlay = input.nextInt();
        // create a variable to hold the cpu response generated by the getCPUResponse() method.
        int cpuPlay = getCPUResponse();

        //compare user and cpu response with each other to decide the winner.

        int score = 0;

        switch(playerPlay){
            case 1: Rock rock = new Rock(cpuPlay);
                score = rock.checkOutcome();
                break;
            case 2: Paper paper = new Paper(cpuPlay);
                score = paper.checkOutcome();
                break;
            case 3: Scissors scissors = new Scissors(cpuPlay);
                score = scissors.checkOutcome();
                break;
            default:
                System.out.println("Invalid user response");
        }

        if(score > 0){
            System.out.println("Player wins the round!");
        } else {
            System.out.println("CPU wins the round :(");
        }
        return score;
        
    }

    public int getCPUResponse(){
        // Generate random integers in range 1 to 3

        Random random = new Random();
        int rps = random.nextInt(3 - 1 + 1) + 1;
        return rps;

    }
}